### ISSUE TITLE
API is not recognizing errors

### ISSUE THREAD

**Issue by codeNoobie** [RonB/angular-oboe#12]
On error response (status 500), the Api is not calling the error promise handler. It goes to the success handler with the error content. Is it not being handled right now by the API or I am doing something wrong?

**Comment by RonB** [comment]
Can you include your sourcecode so I can take a look at your problem?

**Comment by RonB** [comment]
can you include your sourcecode so I can take a look?

**Comment by gabriellebourdages** [comment]
I know that this issue has been closed a while ago, but the bug is actually in oboe itself and someone did a PR with a fix for it:
https://github.com/jimhigson/oboe.js/pull/166 
It doesn't seem to be in the latest version released though.

If anyone else encounters the problem (like I did), this should fix it.
